server:
  port: 8888
spring:
  application:
    name: zyh-config
  cloud:
    config:
      server:
        git:
          uri: http://zhuyuhang@172.18.57.233/zhuyuhang/config-repo.git
          default-label: master
        default-profile: dev
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http:/127.0.0.1:9002/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"